version: "3"

services:
  janusgraph:
    image: janusgraph/janusgraph:1.1.0-20240105-102008.1270818
    container_name: janusgraph
    ports:
      - "8182:8182"
  mysql:
    image: mysql:8.3.0-oraclelinux8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
